### ISSUE TITLE
Linux support??

### ISSUE THREAD

**Issue by ehzawad** [SohanChy/SiteSearch-Desktop#1]
How can I build executable in Linux 64 bit?

**Comment by SohanChy** [comment]
You need to link the curl library while compiling.
How to link it will differ from ide to ide.
You need minimum curl version curl-7.40.0
The windows executable was compiled using curl-7.40.0-devel-mingw32

I have written a step by step for [setting up / linking SFML with the CodeBlocks IDE](http://sohanchy.github.io/blog/guides-tuts/how-to-setup-sfml-232-with-codeblocks/) , With curl and other libraries, it should be pretty similar.
